name: Reconciliation tool

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: make install
      - name: Check linting errors
        run: make lint
      - name: Check types
        run: make typing
      - name: Run tests
        run: make test
